FROM debian
MAINTAINER fabrizio2210

ENV APP_FOLDER="/opt/web"

RUN apt-get update && apt-get install -y \
    curl

RUN apt remove -y nodejs nodejs-doc

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

RUN mkdir -p ${APP_FOLDER}/src
COPY src/vue/package.json ${APP_FOLDER}/
COPY src/vue/vite.config.js ${APP_FOLDER}/
COPY src/vue/index.html ${APP_FOLDER}/
COPY src/vue/public/ ${APP_FOLDER}/

RUN cd ${APP_FOLDER} && \
    npm install

# COMMAND
WORKDIR ${APP_FOLDER}
CMD npm run format && npm run dev
